# -*- coding: utf-8 -*-
"""2-Python_Groups_Hands-on.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0zyieqwlHyY_9yFu-gQS_ryzMjskShF

# Python_Groups_Hands-on

## Project: Library Management System
### Description:
- Develop a basic Library Management System (LMS) that allows users to manage book records, including adding, updating, deleting, and displaying book information. The system should also provide basic statistical analysis.

### System requirements:

#### Data Structure Design:

  - Define data structures using lists, tuples, dictionaries, and sets to store book information (e.g., book ID, title, author, year, genres).

#### Basic Operations:

- Implement functions to add, update, delete, and display book records.
- Ensure proper type conversion and validation of inputs.

#### Statistical Analysis:

- Write functions to calculate and display the total number of books, the average publication year, and the most common genre.
- Use list comprehensions and built-in functions (sort, len, zip, range) for calculations.

#### Advanced Features:

- Implement search functionality to find books by title or author using lambda functions.
- Provide sorting options for book records based on different criteria (e.g., title, year).


#### Exception Handling:

- Handle potential errors (e.g., invalid input) using try-except blocks.

#### Q1: Using the following table, create a function to add these books to your library:
- **Note**: Create the data structure first



| Book ID | Title                            | Author               | Year | Genres                              |
|---------|----------------------------------|----------------------|------|-------------------------------------|
| 1       | Harry Potter and the Sorcerer's Stone | J.K. Rowling         | 1997 | Fantasy, Young Adult                |
| 2       | To Kill a Mockingbird             | Harper Lee           | 1960 | Fiction, Classics                   |
| 3       | The Great Gatsby                  | F. Scott Fitzgerald  | 1925 | Fiction, Classics                   |
| 4       | 1984                              | George Orwell        | 1949 | Fiction, Dystopian                  |
| 5       | The Catcher in the Rye            | J.D. Salinger        | 1951 | Fiction, Classics                   |
| 6       | Pride and Prejudice               | Jane Austen          | 1813 | Fiction, Romance, Classics          |
| 7       | The Hobbit                        | J.R.R. Tolkien       | 1937 | Fantasy, Adventure                  |
| 8       | The Hunger Games                  | Suzanne Collins      | 2008 | Science Fiction, Dystopian, Young Adult |
| 9       | The Da Vinci Code                 | Dan Brown            | 2003 | Mystery, Thriller                   |
| 10      | The Chronicles of Narnia          | C.S. Lewis           | 1950 | Fantasy, Children's Literature      |
| 11      | Gone with the Wind                | Margaret Mitchell    | 1936 | Historical Fiction, Romance         |
| 12      | Sapiens: A Brief History of Humankind | Yuval Noah Harari   | 2011 | Nonfiction, History, Science        |
| 13      | The Road                          | Cormac McCarthy      | 2006 | Fiction, Post-Apocalyptic           |
| 14      | The Girl with the Dragon Tattoo   | Stieg Larsson        | 2005 | Mystery, Thriller                   |
| 15      | The Alchemist                     | Paulo Coelho         | 1988 | Fiction, Inspirational              |
"""

from collections import Counter
#استوردنا الكلاس كاونتر من الموديول كولكشنز لان ذا الكلاس يحسب لنا كم مره تكرر شي داخل ديكشنري او ليست مثلا يحسب لنا تكرار الكوميدي في الجينرز

books = {}#عرفنا متغير حطينا فيه ديكشنري جديد فاضي

def add_book(book_id, title, author, year, genres):#عرفنا داله اسمها اد بوك تضيف كتب جديده عن طريق اخذ باراميتيرز لها ك البوك اي دي والتايتل والاوثر واليير والنوع اللي هو جينرز
    books[book_id] = {#نفس المتغير اللي فيه ديكشنري حطي
        "title": title,
        "author": author,
        "year": year,
        "genres": genres
    }

def load_sample_books():
    sample = [
        (1,  "Harry Potter and the Sorcerer's Stone",     "J.K. Rowling",           1997, ["Fantasy","Young Adult"]),
        (2,  "To Kill a Mockingbird",                    "Harper Lee",             1960, ["Fiction","Classics"]),
        (3,  "The Great Gatsby",                         "F. Scott Fitzgerald",    1925, ["Fiction","Classics"]),
        (4,  "1984",                                      "George Orwell",         1949, ["Fiction","Dystopian"]),
        (5,  "The Catcher in the Rye",                   "J.D. Salinger",         1951, ["Fiction","Classics"]),
        (6,  "Pride and Prejudice",                      "Jane Austen",           1813, ["Fiction","Romance","Classics"]),
        (7,  "The Hobbit",                               "J.R.R. Tolkien",        1937, ["Fantasy","Adventure"]),
        (8,  "The Hunger Games",                         "Suzanne Collins",       2008, ["Science Fiction","Dystopian","Young Adult"]),
        (9,  "The Da Vinci Code",                        "Dan Brown",             2003, ["Mystery","Thriller"]),
        (10, "The Chronicles of Narnia",                 "C.S. Lewis",            1950, ["Fantasy","Children's Literature"]),
        (11, "Gone with the Wind",                       "Margaret Mitchell",     1936, ["Historical Fiction","Romance"]),
        (12, "Sapiens: A Brief History of Humankind",    "Yuval Noah Harari",     2011, ["Nonfiction","History","Science"]),
        (13, "The Road",                                 "Cormac McCarthy",       2006, ["Fiction","Post-Apocalyptic"]),
        (14, "The Girl with the Dragon Tattoo",          "Stieg Larsson",         2005, ["Mystery","Thriller"]),
        (15, "The Alchemist",                            "Paulo Coelho",          1988, ["Fiction","Inspirational"])
    ]
    for b in sample:
        add_book(*b)

load_sample_books()

"""#### Q2: Create a function that updates books exsisted in your library and test it.
- **Note**: If the user entered wrong book ID it should print "Book with ID 'num' does not exist.
"""

def update_book(book_id, **fields):
    if book_id in books:
        books[book_id].update(fields)
        print("Update:", book_id)
    else:
        print(f"Book with ID {book_id} does not exist.")

update_book(1, title="New Title")
print(books)

"""#### Q3: Create a function to delete books from your library and test it."""

def delete_book(book_id):
    if book_id in books:
        del books[book_id]
        print("Deleted:", book_id)
    else:
        print(f"Book with ID {book_id} does not exist.")

delete_book(15)
print(books)

"""#### Q4: Create functions to do the following: calculates and display the total number of books, the average publication year, and the most common genre. and test it."""

from collections import Counter

def total_books():
    print("Total books:", len(books))

def average_year():
    yrs = [b["year"] for b in books.values()]
    print("Average year:", sum(yrs)//len(yrs))

def most_common_genre():
    cnt = Counter(g for b in books.values() for g in b["genres"])
    genre, _ = cnt.most_common(1)[0]
    print(" Top genre:", genre)

total_books()
average_year()
most_common_genre()

"""#### Q5: Create 2 functions to search for books by the title and the author from your library and test it."""

find_by_title  = lambda kw: [b for b in books.values() if kw.lower() in b["title"].lower()]
find_by_author = lambda kw: [b for b in books.values() if kw.lower() in b["author"].lower()]

print("Search title ‘the’:", find_by_title("the"))
print("Search author ‘lee’:", find_by_author("lee"))

"""#### Q6: Create 2 functions to sort the books by the title and the year from your library and test it."""

def sort_by_title():
    return sorted(books.values(), key=lambda b: b["title"])

def sort_by_year():
    return sorted(books.values(), key=lambda b: b["year"])

print("by title:", sort_by_title())
print("by year:",  sort_by_year())

"""#### Q7: Create a function to bulk update genres of books using list comprehension. and test it."""

def bulk_update_genres(old_genre, new_genre):

    for book in books.values():
        book["genres"][:] = [
            new_genre if g == old_genre else g
            for g in book["genres"]
        ]

books.clear()
load_sample_books()

print("Before:", [b["genres"] for b in books.values() if "Dystopian" in b["genres"]])

bulk_update_genres("Dystopian", "Action")

print(" After:", [b["genres"] for b in books.values() if "Action" in b["genres"]])

"""#### Q8: Implement a function to generate a report summarizing the library's statistics, including the total number of books, the number of books by each author, the number of books in each genre, and the oldest and newest books. and test it."""

def generate_report():
    total = len(books)
    by_author = Counter(b["author"] for b in books.values())
    by_genre  = Counter(g for b in books.values() for g in b["genres"])
    years     = [b["year"] for b in books.values()]
    print("report")
    print("Total books:", total)
    print("By author:", dict(by_author))
    print("By genre:",  dict(by_genre))
    print("Oldest:", min(years))
    print("Newest:", max(years))

generate_report()

